In [79]:
# установка библиотек
# !pip install sklearn
# !pip install scipy
#!pip install seaborn

In [4]:
# подключение необходимых библиотек
from sklearn import linear_model
import numpy as np

from scipy.stats import pearsonr
#import seaborn

In [5]:
# задание иксов - двумерный массив.
# x1 - первый столбец, x2 - второй столбец и т.д
# для примера взяты случайные числа
# объём выборки - 30 элементов (строк)

x = np.array([[34.92936742,  7.98349832, 97.80160879, 85.46764662],
       [32.63921263, 50.73287081, 55.67302694, 63.05747896],
       [46.72788077, 50.43879405, 40.01162268, 42.17610393],
       [86.84573374, 66.77429379, 33.05048926, 53.46967138],
       [12.97589339, 58.68833902, 80.7027337 , 11.82115068],
       [82.40900842, 85.27988962, 59.22490509, 59.32385429],
       [79.99088397,  8.40201079, 61.05786324,  5.44363563],
       [35.07824122, 41.51445571, 56.94820992, 64.87094119],
       [23.24661153, 17.41146655, 15.39180062, 57.31989222],
       [65.41563805, 83.4534294 , 20.43266023, 10.40942717],
       [ 4.80475156, 37.44892583,  0.84919028, 17.06361212],
       [99.0675275 , 32.0132231 , 21.64496779, 85.82513532],
       [67.88130639, 89.42707592, 78.98258011, 17.14347141],
       [25.30909249, 62.54567099, 50.48100437,  7.25112004],
       [55.31032076, 87.75760319, 95.41122743, 18.15428723],
       [92.29829594, 86.0365853 , 77.52501972, 69.94388878],
       [71.15101056, 69.5064989 , 32.36465328, 54.07575496],
       [93.81127408, 79.28645966, 72.87496118, 71.04137687],
       [ 6.9351043 , 64.19284538, 27.48084438, 18.76945571],
       [23.56098088, 89.84002283, 56.38296068, 72.02376112],
       [ 5.39651864,  5.20876626, 14.06641307, 97.51071988],
       [86.71915785, 59.39499172, 69.49072637, 48.63676737],
       [66.50047314,  3.45372372, 97.27819998, 91.42877441],
       [91.81603652, 54.75822596, 17.73648165, 39.48688266],
       [19.16629266, 95.18608528, 91.62312494, 58.39848222],
       [67.84474405, 92.68781518, 86.32099877, 41.38283058],
       [ 7.41590552, 38.05204806, 54.94065239, 85.59862295],
       [ 9.86488852, 13.85259944, 15.35361164, 17.88568294],
       [42.50620937, 69.1572641 , 52.19125136, 25.38788708],
       [72.25255248, 54.29264925, 47.56740548, 37.98250037]])

# задание игреков - одномерный массив

y = np.array([50.4260844 , 97.13314426, 41.48640132, 51.29986203, 92.2344315 ,
       81.06717161, 76.81755724, 28.14742411, 33.84613082, 20.24220197,
       92.27376406, 99.91217919, 69.29245622, 42.57232511, 78.99563729,
       69.10384888, 21.02463117, 19.30924377,  3.66177688,  1.27747803,
       85.18261657, 65.12369309, 53.65666134, 79.38890871, 84.34927708,
       44.72246265,  1.80450751, 86.76951995, 91.19709751, 71.57040561])

# создание объекта для построения линейной регрессии
reg = linear_model.LinearRegression()

# построение уравнения линейной регрессии.
# в объекте reg будет сохранено уравнение регрессии
reg.fit( x, y )

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [82]:
# коэффициенты перед иксами
reg.coef_

array([ 0.1862102 , -0.33003302,  0.11458164, -0.29064437])

In [83]:
# свободный член уравнения регрессии
reg.intercept_

74.42904667328622

Получается такое уравнение:

$y =  0.1862102 x_1 -0.33003302 x_2 + 0.11458164 x_3 - 0.29064437 x_4 + 74.42904667706705$

In [84]:
# подстановка четырёх иксов в полученное уравнение
# ответ будет на экране
reg.predict( [[11, 12, 13, 14]] )

array([69.93750286])

In [85]:
# оценка уравнения регрессии. вычисление коэффициента детерминации (от 0 до 1)
# коф. детерминацияи - это коэф. корреляции (множественной для данного случая) возведённый в квадрат
# чем ближе к 1 тем лучше
reg.score(x,y)

0.11195854603039657

In [86]:
# оценка регрессии по средней абсолютной ошибке
# вычислим игреки по уравнению
y_pred = reg.predict(x)

далее вычислим среднюю абсолтную ошибку:
    
$ \frac{1}{n} \sum | y_{истинное} - y_{предсказанное} |  $

In [87]:
np.mean( np.abs(y - y_pred) )

25.192877411527103

## Линейный коэф. кор. между иксами и y

In [88]:
# линейный коэф. корреляции между Y и X1
pearsonr(x[:,0],y)

(0.10476248412590577, 0.581670961140817)

коэффициент корреляции: 0.10476248412590576

p-value: 0.5816709611408178 - вероятность получить такой или более выраженный коэф. кор. в выборочных данных, когда в генеральной совокупности корреляция отсутствует (согласно документации, на p-value рекомендуется полагаться когда объём выборки >500)

In [89]:
pearsonr(x[:,1],y)

(-0.1612143305849406, 0.3947281754718861)

In [90]:
pearsonr(x[:,2],y)

(0.01403733224125381, 0.9413110791226587)

In [91]:
pearsonr(x[:,3],y)

(-0.15006577197913845, 0.4286429937955012)

In [92]:
# документация по функции perasonr
help(pearsonr)

Help on function pearsonr in module scipy.stats.stats:

pearsonr(x, y)
    Calculate a Pearson correlation coefficient and the p-value for testing
    non-correlation.
    
    The Pearson correlation coefficient measures the linear relationship
    between two datasets. Strictly speaking, Pearson's correlation requires
    that each dataset be normally distributed, and not necessarily zero-mean.
    Like other correlation coefficients, this one varies between -1 and +1
    with 0 implying no correlation. Correlations of -1 or +1 imply an exact
    linear relationship. Positive correlations imply that as x increases, so
    does y. Negative correlations imply that as x increases, y decreases.
    
    The p-value roughly indicates the probability of an uncorrelated system
    producing datasets that have a Pearson correlation at least as extreme
    as the one computed from these datasets. The p-values are not entirely
    reliable but are probably reasonable for datasets larger than 5

## Матрица корреляции 
Корреляция всех со всеми

In [93]:
# доплним матрицу из иксов столбцом из y
# результат запишем в переменную data
data = np.insert(x, 4, values=y, axis=1)

In [94]:
# выведем данные
data

array([[34.92936742,  7.98349832, 97.80160879, 85.46764662, 50.4260844 ],
       [32.63921263, 50.73287081, 55.67302694, 63.05747896, 97.13314426],
       [46.72788077, 50.43879405, 40.01162268, 42.17610393, 41.48640132],
       [86.84573374, 66.77429379, 33.05048926, 53.46967138, 51.29986203],
       [12.97589339, 58.68833902, 80.7027337 , 11.82115068, 92.2344315 ],
       [82.40900842, 85.27988962, 59.22490509, 59.32385429, 81.06717161],
       [79.99088397,  8.40201079, 61.05786324,  5.44363563, 76.81755724],
       [35.07824122, 41.51445571, 56.94820992, 64.87094119, 28.14742411],
       [23.24661153, 17.41146655, 15.39180062, 57.31989222, 33.84613082],
       [65.41563805, 83.4534294 , 20.43266023, 10.40942717, 20.24220197],
       [ 4.80475156, 37.44892583,  0.84919028, 17.06361212, 92.27376406],
       [99.0675275 , 32.0132231 , 21.64496779, 85.82513532, 99.91217919],
       [67.88130639, 89.42707592, 78.98258011, 17.14347141, 69.29245622],
       [25.30909249, 62.54567099, 50.4

In [95]:
# матрица корреляции каждой величины с каждой
np.corrcoef(data.T)
# первая строка - коэф. кор. x1 c велечинами x1, x2, x3, x4 и y
# вторая строка - коэф. кор. x2 c велечинами x1, x2, x3, x4 и y
# и т.д.

array([[ 1.        ,  0.26837166,  0.18521147,  0.08886629,  0.10476248],
       [ 0.26837166,  1.        ,  0.28665881, -0.26393303, -0.16121433],
       [ 0.18521147,  0.28665881,  1.        ,  0.14287257,  0.01403733],
       [ 0.08886629, -0.26393303,  0.14287257,  1.        , -0.15006577],
       [ 0.10476248, -0.16121433,  0.01403733, -0.15006577,  1.        ]])

In [1]:
from factor_analyzer import FactorAnalyzer

In [2]:
fa = FactorAnalyzer()

In [6]:
fa.fit(x)

FactorAnalyzer(bounds=(0.005, 1), impute='median', is_corr_matrix=False,
        method='minres', n_factors=3, rotation='promax',
        rotation_kwargs={}, use_smc=True)

In [8]:
fa.get_eigenvalues()

(array([1.49915276, 1.18934779, 0.81530867, 0.49619078]),
 array([ 0.92270082,  0.68970764,  0.23318143, -0.05838853]))